version: '3.9'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    env_file:
      - .env
        
  django_app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis

  
  

