# Generated by Django 4.2.4 on 2023-08-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiWeekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.IntegerField(db_index=True)),
                ('username', models.CharField(max_length=30)),
                ('lang', models.CharField(max_length=30)),
                ('page', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.IntegerField(db_index=True)),
                ('username', models.CharField(max_length=30)),
                ('lang', models.CharField(max_length=30)),
                ('page', models.IntegerField(db_index=True)),
            ],
        ),
    ]
